apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: mariadb-nfs-pv
  resources:
    requests:
      storage: 20Gi
