apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: wordpress-nfs-pv
  resources:
    requests:
      storage: 10Gi
